package service

var sayingsEn = []string{
	"Let's see weather or not you should leave umbrella at home.",
	"The best and the worst thing about the weather is that it changes.",
	"Conversation about the weather is the last refuge of the unimaginative.",
	"Weather forecast for tonight: dark.",
	"There is no such thing as bad weather, only different kinds of good weather.",
	"I've lived in good climate, and it bores the hell out of me.",
	"Do you know that bad weather always looks worse through a window?",
}

var monthsEn = map[string]string{
	"01": "January",
	"02": "February",
	"03": "March",
	"04": "April",
	"05": "May",
	"06": "June",
	"07": "July",
	"08": "August",
	"09": "September",
	"10": "October",
	"11": "November",
	"12": "December",
}

var commentsEn = map[string]string{
	"no":                "👒 No danger to the average person.",
	"little":            "👓 Little risk of harm.",
	"high":              "☝ High risk of harm.",
	"vhigh":             "☝☝ Very high risk of harm.",
	"extreme":           "❌ Extreme risk of harm. Stay indors!",
	"hat":               "Wear a hat and/or sunglasses.",
	"spf15":             "Use SPF 15+ Sunscreen.",
	"spf30":             "Use SPF 30+ Sunscreen.",
	"spf50":             "Use SPF 50 Sunscreen.",
	"cover":             "Cover the body with clothing. Avoid the sun if possible.",
	"sunburn":           "Sun burn time is",
	"DefaultMessage":    "Hi! I am WeartheBot and I cannot spell.",
	"CoordsAccepted":    "Gotcha! Please choose the forecast period.",
	"DiffPlaceAccepted": "Right. Please send me the name of the place.",
	"ChooseLocation":    "What interests you most now?",
	"ChoosePeriodType":  "How would you like your weather forecast?",
	"ChoosePeriod":      "How far in the future shall we have a look?",
	"End":               "Bye! Have a nice day!",
	"Unknown":           "Sorry, did not quite get you.",
	"TryAgain":          "Sorry, the place with such name was not found. Please try again.",
	"AtMyLocation":      "Weather at my location",
	"AtADiffPlace":      "Weather elsewhere",
	"Back0":             "< Back",
	"Back1":             "<< Back",
	"ByDays":            "By Days",
	"ByHours":           "By Hours",
	"Now":               "Now",
	"3Days":             "3 days",
	"5Days":             "5 days",
	"7Days":             "7 days",
	"10Days":            "10 days",
	"16Days":            "16 days",
	"24Hours":           "24 hours",
	"48Hours":           "48 hours",
	"72Hours":           "72 hours",
	"96Hours":           "96 hours",
	"120Hours":          "120 hours",
}

// TODO split with space and only use the first part
var timePeriodsEn = map[string]int{
	"3 days":    3,
	"5 days":    5,
	"7 days":    7,
	"10 days":   10,
	"16 days":   16,
	"24 hours":  24,
	"48 hours":  48,
	"72 hours":  72,
	"96 hours":  96,
	"120 hours": 120,
}
